### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by joker1138** [Copterdoctor/EDAgent.net#1]
Adding Edsm Api for when adding a commander doesn’t seem to work. I get “profile retrieval error, no credits stored”

**Comment by Copterdoctor** [comment]
Have you just recently created an EDSM profile? It can take a bit of time for your profile to fully update from the game journal logs.

I'll put in a fix so the reference still creates if there are no credits information coming from EDSM. Thats an oversite on my end.

**Comment by joker1138** [comment]
That was it!  Can link the app just fine now. Thanks!

**Comment by bajastar** [comment]
Hi excellent. Do you have any info about odisey
